name: Deploy Outage Watcher

on:
  workflow_dispatch:          # manual trigger
  schedule:
    - cron: "*/30 * * * *"    # every 30 minutes

permissions:
  contents: write   # needed to push to gh-pages
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run outage watcher
        run: python outage_watcher.py

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch:_

